name: LittleSkinLogin
version: '${project.version}'
main: cn.paper_card.little_skin_login.ThePlugin
api-version: '1.20'
folia-supported: true
author: Paper99

depend:
  - Database

commands:
  little-skin:
    permission: little-skin.command

permissions:
  little-skin.command:
    default: op
