name: LittleSkinLogin
version: '${project.version}'
main: cn.paper_card.little_skin_login.LittleSkinLogin
api-version: '1.20'
folia-supported: true
author: Paper99

commands:
  little-skin:
    permission: little-skin.command

permissions:
  little-skin.command:
    default: true
